### PR TITLE
Update to bootstrap 4.1

### PR DESCRIPTION
**Pull request by boardfish**
These snippets have been using alpha2 for the longest time, so I updated them to use the CDN links from [getbootstrap.com](https://getbootstrap.com). Note that I haven't checked each individual snippet for compatibility with the changes, but I doubt much has significantly changed that would affect individual components in these snippets.

### CODE REVIEW

**Comment by jvanja** [comment]
Thanks for the PR @boardfish! I noticed in the Ultisnips snippets you deleted the `endsnippet` lines like [here](https://github.com/jvanja/vim-bootstrap4-snippets/pull/2/files#diff-ba5705896ee433876ec899292b88c768L20), The `endsnippet` [is necessary to end the snippet block](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L628). 
Can you please fix and resubmit? 
Thanks again!

**Comment by jvanja** [comment]
Also, since Bootstrap is now out of beta we could just change the CDN links to 4.0.0?

**Comment by boardfish** [comment]
Ah, gotcha. I think I'll be able to do that this weekend, and I'll also see where major changes have been made from `alpha2` to now - there are a few I can name, like `card-block` becoming `card-body`.

**Comment by boardfish** [comment]
There's the first part sorted - I think I was running under the assumption that syntax for all snippet engines was the same. It'd make a lot of sense for them all to just rely on being indented one step past the `snippet foo` call.

I'd like to use the snippets a lot more but it's hard to remember some expansions. Is `cat .vim/bundle/vim-bootstrap4-snippets/html/foo | grep snippet` the best way to do that still, or is there a way to look them up while you're inside Vim?

**Comment by jvanja** [comment]
Thanks for the update. 
As for listing the snippets, at this point I remembered the snippets I use the most and then for anything new I just try a trigger that makes sense to me (which usually works)... This works for me but if you want something more reliable, I would suggest creating a key map to trigger this [function](https://github.com/SirVer/ultisnips/blob/423f264e753cec260b4f14455126e6db7ba429af/doc/UltiSnips.txt#L528-L541). That should give you the list of available snippets for the current buffer.. Then you could maybe drop that into quickfix list.. 
Hope this helps!

**Comment by jvanja** [comment]
@boardfish There is actually a pretty brilliant way of exploring available snippets for a given file type but it requires using [FZF](https://github.com/junegunn/fzf.vim). When you have an open file, you can just go `:Snippets` and FZF will open a preview window where you can fuzzy find snippets! I just discovered this and my mind exploded...

**Pull request closed without merging**
